# Generated by Django 3.2.4 on 2023-11-27 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='attachment',
        ),
    ]
